import puppeteer from 'puppeteer';
const b = await puppeteer.launch({ headless: 'new' });
const p = await b.newPage();
await p.setViewport({ width: 1280, height: 720 });
await p.goto('http://localhost:5199/', { waitUntil: 'domcontentloaded', timeout: 40000 });
await p.waitForFunction('!!window.__dbg?.effects', { timeout: 40000 });
await new Promise(r => setTimeout(r, 1500));
await p.evaluate(() => document.querySelector('[data-pack=boxing]').click());
await new Promise(r => setTimeout(r, 800));
await p.evaluate(() => document.getElementById('btn-view')?.click());
await new Promise(r => setTimeout(r, 900));
await p.screenshot({ path: 'tmp_fp_bx.jpg', type: 'jpeg', quality: 88 });
console.log('ok');
await b.close(); process.exit(0);
